name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and restart bot
        run: |
          cd ~/codebases/discord_bot
          git reset --hard
          git pull origin main
          ./venv/bin/pip install -r requirements.txt
          pm2 restart discord-bot || pm2 start bot.py --name discord-bot --interpreter ./venv/bin/python
