name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and restart bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEYS }}
          script: |
            cd ~/codebases/discord_bot
            git reset --hard
            git pull origin master
            ./venv/bin/pip install -r requirements.txt
            pm2 restart discord-bot || pm2 start bot.py --name discord-bot --interpreter ./venv/bin/python
